apiVersion: v1
kind: Service
metadata:
  name: api 
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-backend-fastapi
          image: aagustinconti/fast-api-products:latest #DockerHub repo
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
          - name: MYSQL_HOST
            value: mysql-0.mysql-headless.default.svc.cluster.local
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: api
          - name: DATABASE_URI
            value: 'mysql+pymysql://root:root@mysql-0.mysql-headless.default.svc.cluster.local:3306/todo'
