apiVersion: v1
kind: Service
metadata:
  name: ui 
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: api-frontend-node
          image: aagustinconti/ui-node-products:latest # DockerHub repo
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
          # <service-name>.<namespace>.svc.cluster.local:<service-port>
          - name: API_URL
            value: 'http://api:8000'
          - name: PORT
            value: '80'
