version: "3.1"

services:
  mysqldb:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      dockerfile: ./app/Dockerfile
      context: .
    image: tcp-ip
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysqldb
    depends_on:
      - mysqldb
    ports:
      - "8000:8000"

  ui:
    build:
      context: ./ui
    image: ui-tcp-ip
    restart: always
    environment:
      API_URL: http://api:8000
      PORT: 80
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db:
