---

- name: Update apt cache
  apt:
    update_cache: yes


- name: Debug variables
  debug:
    msg: "- ansible_hostname: {{ansible_hostname}}  - inventory_hostname: {{inventory_hostname}}  - ansible_fqdn: {{ansible_fqdn}}  - ansible_ssh_host: {{ansible_ssh_host}}"

- name: Change the hostname to our standard
  hostname:
    name: "{{ inventory_hostname }}"

- name: Replace a localhost entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 {{inventory_hostname}} {{ansible_hostname}} localhost"
    owner: root
    group: root
    mode: '0644'

- name: Remove vagrant default configuration
  lineinfile:
    dest:  /etc/hosts
    state:  absent
    regexp: '^127\.0\.2\.1'

- name: Add entries to /etc/hosts (master node)
  lineinfile:
    path: /etc/hosts
    line: "{{ CONTROL_IP }} master-node-{{ (IP_START | int) }}"

- name: Add entries to /etc/hosts (worker nodes)
  lineinfile:
    path: /etc/hosts
    line: "{{ IP_SECTIONS }}{{ (IP_START | int + item | int) }} worker-node-{{  (IP_START | int + item | int) }}"
  with_sequence: start=1 end="{{ (NUM_WORKER_NODES | int) }}"


- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 180
  when: PROD_TEST 

- name: Read /etc/hosts file
  command: "cat /etc/hosts"
  register: out

- name: Debug /etc/hosts
  debug:
    msg: "{{ out.stdout_lines }}"
